#ifndef _PINMAP_H_
#define _PINMAP_H_

#define BOOSTER_LEFT_UP 15
#define BOOSTER_LEFT_DOWN 14
#define BOOSTER_LEFT_LEFT 13
#define BOOSTER_LEFT_RIGHT 12
#define BOOSTER_LEFT_BTN 11

#define BOOSTER_RIGHT_UP 16
#define BOOSTER_RIGHT_DOWN 17
#define BOOSTER_RIGHT_LEFT 18
#define BOOSTER_RIGHT_RIGHT 19
#define BOOSTER_RIGHT_BTN 20

#endif